css-two-column-layout - Brandon Chin
brandonechin/c1222-code-solutions pull request #20
Opened 2022-12-09 23:02 UTC by brandonechin

<img width="624" alt="2022-12-09 15_02_04-CSS Challenge - Two Column Layout" src="https://user-images.githubusercontent.com/111926994/206809322-643bfc53-6ed6-4b2e-ba8d-e15c03830a83.png">

2022-12-12 23:45 UTC, codingcodymiller requested changes

2022-12-12 23:45 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="row col-half">
No one element should be both a `row` and a `column`. Instead, you should give this `column-half` a child with the `row` class

2022-12-13 00:13 UTC, brandonechin commented
![2022-12-12 16_13_08-index html - c1222-code-solutions  Dev Container  - Visual Studio Code](https://user-images.githubusercontent.com/111926994/207192134-db0acc5f-79d4-4c11-9385-045e71ed02c2.png)

2022-12-13 17:33 UTC, codingcodymiller approved these changes

2022-12-14 05:05 UTC, merged